CREATE VIEW DashboardReporting.CommitmentStatementDashboardView
AS
SELECT
    Id,
    ApprenticeshipId,
    CommitmentsApprenticeshipId,
    CommitmentsApprovedOn,
    EmployerAccountLegalEntityId,
    EmployerName,
    TrainingProviderId,
    TrainingProviderName,
    CourseName,
    CourseLevel,
    CourseOption,
    PlannedStartDate,
    PlannedEndDate,
    TrainingProviderCorrect,
    EmployerCorrect,
    RolesAndResponsibilitiesCorrect,
    ApprenticeshipDetailsCorrect,
    HowApprenticeshipDeliveredCorrect,
    ConfirmBefore,
    ConfirmedOn,
    CourseDuration,
    LastViewed,
    CreatedOn
FROM
    dbo.Revision
GO