trigger:
  batch: true
  branches:
    include:
      - "main"

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/1.0.7
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
  - template: pipeline-templates/job/dacpac-build.yml

- template: azure-pipelines-templates/deploy/stage/nuget-publish.yml@das-platform-building-blocks
