jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration Agents
    demands: LATEST_DOTNET_VERSION -equals 3.1
  variables:
  - group: BUILD Management Resources
  - name: buildConfiguration
    value: release
  workspace:
    clean: all
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
        SonarCloudProjectKey: SkillsFundingAgency_das-apprentice-commitments-api
      
  - template: azure-pipelines-templates/build/step/dependency-check.yml@das-platform-building-blocks

  - task: DotNetCoreCLI@2
    displayName: Publish Apprentice Commitments Api
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.ApprenticeCommitments.Api/SFA.DAS.ApprenticeCommitments.Api.csproj
      arguments: --configuration release --output $(build.artifactstagingdirectory)/publish --no-restore --no-build

  - task: CopyFiles@2
    displayName: Copy Files to $(build.artifactstagingdirectory)/publish
    inputs:
      contents: |
        azure/**
      targetFolder: $(build.artifactstagingdirectory)/publish
      overWrite: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Artifact - ApprenticeCommitmentsApi
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: ApprenticeCommitmentsApi

  - template: azure-pipelines-templates/build/step/nuget-pack.yml@das-platform-building-blocks
    parameters:
      DotNetStandardPackagesToPack: |
        src/SFA.DAS.ApprenticeCommitments.Messages/SFA.DAS.ApprenticeCommitments.Messages.csproj