jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration
  variables:
  - group: Prod Management Resources
  workspace:
    clean: all
  steps:
  - task: UseGitVersion@5
    displayName: GitVersion
    inputs:
      versionSpec: 5.x
      useConfigFile: true
      configFilePath: GitVersion.yml

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/dependency-check.yml@das-platform-building-blocks

  - task: DotNetCoreCLI@2
    displayName: Publish Apprentice Commitments Api
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.ApprenticeCommitments.Api/SFA.DAS.ApprenticeCommitments.Api.csproj
      arguments: --configuration release --output $(build.artifactstagingdirectory)/publish --no-restore --no-build

  - task: CopyFiles@2
    displayName: Copy Files to $(build.artifactstagingdirectory)/publish
    inputs:
      contents: |
        azure/**
      targetFolder: $(build.artifactstagingdirectory)/publish
      overWrite: true